server {
    listen 80;
    root /usr/share/nginx/html;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "no-cache, must-revalidate";
    location / {
        try_files $uri =404;
    }
}
